#!/usr/bin/env python3
"""
Deterministic generator for src/chartdata/*.json + *.ts, mirroring the
generation spec in digital-growth-charts-server's chart_data_cache.py
(same reference/sex/measurement-method matrix, same create_chart() calls)
against a pinned rcpchgrowth version (see requirements.txt).

Only a subset of the full src/chartdata/ catalogue is mapped so far - see
MANIFEST below and spec/roadmap.md R12. Do not add an entry to MANIFEST
without verifying it against the existing file's structure; a wrong
mapping silently ships wrong clinical chart lines.
"""

import json
from pathlib import Path

from rcpchgrowth import chart_functions, constants

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "src" / "chartdata"

# The centile format used per file was reverse-engineered by diffing generator
# output against the currently committed files - do not assume any file uses
# COLE_TWO_THIRDS_SDS_NINE_CENTILES just because the export name says
# "CentileData"; verify against the committed data before trusting a mapping.
#
# Height/weight: THREE_PERCENT_CENTILES (despite the name, this collection is
#   [3, 5, 10, 25, 50, 75, 90, 95, 97]) - verified byte-identical against the
#   committed files.
#
# BMI and OFC are intentionally NOT yet in this manifest - both have real,
# understood-but-unresolved discrepancies against the committed files that a
# parameter fix does not explain, so regenerating them needs a maintainer
# decision plus a visual rendering review first (see spec/roadmap.md R12):
#
# - BMI: the correct thirteen-value centile list was found (the
#   EIGHTY_FIVE_PERCENT_CENTILE_COLLECTION, whose own comment says "use for
#   CDC Extended BMI centiles 2022", with a leading 3rd centile prepended -
#   matches the committed centile *set* exactly), but a fresh generation
#   returns `data: []` for cdc_infant (CDC does not define BMI-for-age under
#   2 years) where the committed files have `data: null`. That's a semantic
#   difference (an empty-but-successful result vs "could not be computed"),
#   possibly from a change in rcpchgrowth's error handling since the
#   committed files were generated - not just a formatting difference.
# - OFC: the correct seven-value custom centile list was found
#   ([3, 10, 25, 50, 75, 90, 97] - matches the committed centile set exactly),
#   but the generated age-grid points themselves differ from committed data
#   (e.g. age 0.0192y vs 0.0417y for the second point). Root cause not yet
#   identified.
MANIFEST = [
    ("cdc_height_female_centile_data", constants.CDC, constants.HEIGHT, constants.FEMALE, constants.THREE_PERCENT_CENTILES, "cdcHeightFemaleCentileData"),
    ("cdc_height_male_centile_data", constants.CDC, constants.HEIGHT, constants.MALE, constants.THREE_PERCENT_CENTILES, "cdcHeightMaleCentileData"),
    ("cdc_weight_female_centile_data", constants.CDC, constants.WEIGHT, constants.FEMALE, constants.THREE_PERCENT_CENTILES, "cdcWeightFemaleCentileData"),
    ("cdc_weight_male_centile_data", constants.CDC, constants.WEIGHT, constants.MALE, constants.THREE_PERCENT_CENTILES, "cdcWeightMaleCentileData"),
]


def generate_segments(reference: str, measurement_method: str, sex: str, centile_format) -> list:
    """Return create_chart()'s segment list, with the always-empty/unlicensed
    'fenton' placeholder segment dropped (see roadmap R11)."""
    segments = chart_functions.create_chart(
        reference,
        centile_format=centile_format,
        measurement_method=measurement_method,
        sex=sex,
    )
    return [segment for segment in segments if constants.FENTON not in segment]


def write_json(basename: str, segments: list) -> Path:
    json_path = OUTPUT_DIR / f"{basename}.json"
    json_path.write_text(json.dumps(segments, indent=4) + "\n")
    return json_path


def write_ts_wrapper(basename: str, const_name: str) -> Path:
    ts_path = OUTPUT_DIR / f"{basename}.ts"
    ts_path.write_text(
        "// Generated by chart-data-generation/generate.py. Do not hand-edit; "
        "see spec/roadmap.md R12.\n"
        "import { ReferenceGroup, Reference } from '../interfaces/CentilesObject';\n"
        f"import centileData from './{basename}.json';\n"
        f"export const {const_name}: ReferenceGroup = {{ centile_data: centileData as Reference[] }};\n"
    )
    return ts_path


def main() -> None:
    for basename, reference, measurement_method, sex, centile_format, const_name in MANIFEST:
        segments = generate_segments(reference, measurement_method, sex, centile_format)
        json_path = write_json(basename, segments)
        ts_path = write_ts_wrapper(basename, const_name)
        print(f"wrote {json_path.relative_to(OUTPUT_DIR.parent.parent.parent)}")
        print(f"wrote {ts_path.relative_to(OUTPUT_DIR.parent.parent.parent)}")


if __name__ == "__main__":
    main()
