import { Measurement } from '../../interfaces/RCPCHMeasurementObject';

export const ukwhoBMIBoyHigh: Measurement[] = [
    {
        birth_data: {
            birth_date: '2020-12-01',
            gestation_weeks: 40,
            gestation_days: 0,
            estimated_date_delivery: '2020-12-01',
            estimated_date_delivery_string: 'Tue 01 December, 2020',
            sex: 'male',
        },
        measurement_dates: {
            observation_date: '2028-11-01',
            chronological_decimal_age: 7.917864476386037,
            corrected_decimal_age: 7.917864476386037,
            chronological_calendar_age: '7 years and 11 months',
            corrected_calendar_age: '7 years and 11 months',
            corrected_gestational_age: { corrected_gestation_weeks: null, corrected_gestation_days: null },
            comments: {
                clinician_corrected_decimal_age_comment: 'Born at term. No correction has been made for gestation.',
                lay_corrected_decimal_age_comment: 'Your child was born on their due date.',
                clinician_chronological_decimal_age_comment: 'Born Term. No correction has been made for gestation.',
                lay_chronological_decimal_age_comment: 'Your child was born on their due date.',
            },
            corrected_decimal_age_error: null,
            chronological_decimal_age_error: null,
        },
        child_observation_value: { measurement_method: 'bmi', observation_value: 42.0, observation_value_error: null },
        measurement_calculated_values: {
            corrected_sds: 4.730199788386596,
            corrected_centile: 99.9999,
            corrected_centile_band:
                'This body mass index measurement is well outside the normal range. Please check its accuracy.',
            chronological_sds: 4.730199788386596,
            chronological_centile: 99.9999,
            chronological_centile_band:
                'This body mass index measurement is well outside the normal range. Please check its accuracy.',
            corrected_measurement_error: null,
            chronological_measurement_error: null,
            corrected_percentage_median_bmi: 267.01810138811237,
            chronological_percentage_median_bmi: 267.01810138811237,
        },
        plottable_data: {
            centile_data: {
                chronological_decimal_age_data: {
                    x: 7.917864476386037,
                    y: 42.0,
                    b: null,
                    centile: 99.9999,
                    sds: 4.730199788386596,
                    bone_age_label: null,
                    events_text: null,
                    bone_age_type: null,
                    bone_age_sds: null,
                    bone_age_centile: null,
                    observation_error: null,
                    age_type: 'chronological_age',
                    calendar_age: '7 years and 11 months',
                    lay_comment: 'Your child was born on their due date.',
                    clinician_comment: 'Born Term. No correction has been made for gestation.',
                    age_error: null,
                    centile_band:
                        'This body mass index measurement is well outside the normal range. Please check its accuracy.',
                    observation_value_error: null,
                },
                corrected_decimal_age_data: {
                    x: 7.917864476386037,
                    y: 42.0,
                    b: null,
                    centile: 99.9999,
                    sds: 4.730199788386596,
                    bone_age_label: null,
                    events_text: null,
                    bone_age_type: null,
                    bone_age_sds: null,
                    bone_age_centile: null,
                    observation_error: null,
                    age_type: 'corrected_age',
                    calendar_age: '7 years and 11 months',
                    corrected_gestational_age: '',
                    lay_comment: 'Your child was born on their due date.',
                    clinician_comment: 'Born at term. No correction has been made for gestation.',
                    age_error: null,
                    centile_band:
                        'This body mass index measurement is well outside the normal range. Please check its accuracy.',
                    observation_value_error: null,
                },
            },
            sds_data: {
                chronological_decimal_age_data: {
                    x: 7.917864476386037,
                    y: 4.730199788386596,
                    b: null,
                    centile: 99.9999,
                    sds: null,
                    bone_age_label: null,
                    events_text: null,
                    bone_age_type: null,
                    bone_age_sds: null,
                    bone_age_centile: null,
                    observation_error: null,
                    age_type: 'chronological_age',
                    calendar_age: '7 years and 11 months',
                    lay_comment: 'Your child was born on their due date.',
                    clinician_comment: 'Born Term. No correction has been made for gestation.',
                    age_error: null,
                    centile_band:
                        'This body mass index measurement is well outside the normal range. Please check its accuracy.',
                    observation_value_error: null,
                },
                corrected_decimal_age_data: {
                    x: 7.917864476386037,
                    y: 4.730199788386596,
                    b: null,
                    centile: 99.9999,
                    sds: null,
                    bone_age_label: null,
                    events_text: null,
                    bone_age_type: null,
                    bone_age_sds: null,
                    bone_age_centile: null,
                    observation_error: null,
                    age_type: 'corrected_age',
                    calendar_age: '7 years and 11 months',
                    corrected_gestational_age: '',
                    lay_comment: 'Your child was born on their due date.',
                    clinician_comment: 'Born at term. No correction has been made for gestation.',
                    age_error: null,
                    centile_band:
                        'This body mass index measurement is well outside the normal range. Please check its accuracy.',
                    observation_value_error: null,
                },
            },
        },
        bone_age: {
            bone_age: null,
            bone_age_type: null,
            bone_age_sds: null,
            bone_age_centile: null,
            bone_age_text: null,
        },
        events_data: { events_text: null },
    },
];
