// Generated by chart-data-generation/generate.py. Do not hand-edit; see spec/roadmap.md R12.
import { ReferenceGroup, Reference } from '../interfaces/CentilesObject';
import centileData from './cdc_weight_female_centile_data.json';
export const cdcWeightFemaleCentileData: ReferenceGroup = { centile_data: centileData as Reference[] };
