name: Check build and tests on PR and merge to live

on:
    pull_request:
        branches:
            - '*'
    push:
        branches:
            - live

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v6
            - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: '22.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm install
            - run: npm run build
            - run: npm test
